### ISSUE TITLE
Potential UB

### ISSUE THREAD

**Issue by pepyakin** [fastly/terrarium-rust-guest#2]
You have this code

https://github.com/fastly/terrarium-rust-guest/blob/bf89ba0dd3aab3f9ee49c7a43d0c044a75aba088/src/hostcalls/mod.rs#L458

`from_raw_parts_mut` requires the data pointer (`value_ptr`) to be non-null and properly aligned, even in the case of 0 length slice.

**Comment by pchickey** [comment]
Thanks for the report! I'm glad to see you looking through our code :)

Non-null makes sense, thanks for catching that. The terrarium host-side code (which is not yet open source) won't ever write a null pointer when `found` is true, but we should be defensive against the UB in this guest code by adding an assertion.

I could not recall the alignment rules for Rust's WebAssembly target, but I made a test program to print the alignment of a u8, and it appears to be 1.

**Comment by pepyakin** [comment]
> I could not recall the alignment rules for Rust's WebAssembly target, but I made a test program to print the alignment of a u8, and it appears to be 1.

My pattern dealing with this, is to explicitly check length for 0 and return `&[]`/`Vec::new()` explicitly in that case.

As an aside, I've opened [this issue](https://github.com/rustwasm/team/issues/253) which is related to the code in question, in which you might also be interested.

**Comment by pchickey** [comment]
We are interested, thanks! @jedisct1 designed a similar scheme that we use and his write up about it will be made public soon.

**Comment by pchickey** [comment]
A couple of the other sites where `slice::from_raw_parts` was used turned out to have the null bug. This PR fixes them.

Based on our experiences building Terrarium, we're building a tool to automatically generate the code that unpacks these pointer values into idiomatic Rust values. That work will be happening in an open source repo quite soon, and we'd love to get your input :)
